# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 10:03
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
